// ===== IRREGULAR VERBS (105) =====
const IRREGULAR_VERBS = [
  { base: "arise", past: "arose", pp: "arisen", meaning: "ظهر / نشأ" },
  { base: "awake", past: "awoke", pp: "awoken", meaning: "استيقظ" },
  { base: "be", past: "was/were", pp: "been", meaning: "يكون" },
  { base: "bear", past: "bore", pp: "borne", meaning: "يحتمل / يلد" },
  { base: "beat", past: "beat", pp: "beaten", meaning: "يضرب" },
  { base: "become", past: "became", pp: "become", meaning: "يصبح" },
  { base: "begin", past: "began", pp: "begun", meaning: "يبدأ" },
  { base: "bend", past: "bent", pp: "bent", meaning: "ينحني" },
  { base: "bet", past: "bet", pp: "bet", meaning: "يراهن" },
  { base: "bind", past: "bound", pp: "bound", meaning: "يربط" },
  { base: "bite", past: "bit", pp: "bitten", meaning: "يعض" },
  { base: "bleed", past: "bled", pp: "bled", meaning: "ينزف" },
  { base: "blow", past: "blew", pp: "blown", meaning: "ينفخ" },
  { base: "break", past: "broke", pp: "broken", meaning: "يكسر" },
  { base: "bring", past: "brought", pp: "brought", meaning: "يجلب" },
  { base: "build", past: "built", pp: "built", meaning: "يبني" },
  { base: "burn", past: "burnt", pp: "burnt", meaning: "يحرق" },
  { base: "burst", past: "burst", pp: "burst", meaning: "ينفجر" },
  { base: "buy", past: "bought", pp: "bought", meaning: "يشتري" },
  { base: "cast", past: "cast", pp: "cast", meaning: "يلقي" },
  { base: "catch", past: "caught", pp: "caught", meaning: "يمسك" },
  { base: "choose", past: "chose", pp: "chosen", meaning: "يختار" },
  { base: "cling", past: "clung", pp: "clung", meaning: "يتعلق" },
  { base: "come", past: "came", pp: "come", meaning: "يأتي" },
  { base: "cost", past: "cost", pp: "cost", meaning: "يكلف" },
  { base: "creep", past: "crept", pp: "crept", meaning: "يزحف" },
  { base: "cut", past: "cut", pp: "cut", meaning: "يقطع" },
  { base: "deal", past: "dealt", pp: "dealt", meaning: "يتعامل" },
  { base: "dig", past: "dug", pp: "dug", meaning: "يحفر" },
  { base: "dive", past: "dove", pp: "dived", meaning: "يغوص" },
  { base: "do", past: "did", pp: "done", meaning: "يفعل" },
  { base: "draw", past: "drew", pp: "drawn", meaning: "يرسم" },
  { base: "dream", past: "dreamt", pp: "dreamt", meaning: "يحلم" },
  { base: "drink", past: "drank", pp: "drunk", meaning: "يشرب" },
  { base: "drive", past: "drove", pp: "driven", meaning: "يقود" },
  { base: "eat", past: "ate", pp: "eaten", meaning: "يأكل" },
  { base: "fall", past: "fell", pp: "fallen", meaning: "يسقط" },
  { base: "feed", past: "fed", pp: "fed", meaning: "يطعم" },
  { base: "feel", past: "felt", pp: "felt", meaning: "يشعر" },
  { base: "fight", past: "fought", pp: "fought", meaning: "يقاتل" },
  { base: "find", past: "found", pp: "found", meaning: "يجد" },
  { base: "flee", past: "fled", pp: "fled", meaning: "يهرب" },
  { base: "fly", past: "flew", pp: "flown", meaning: "يطير" },
  { base: "forbid", past: "forbade", pp: "forbidden", meaning: "يمنع" },
  { base: "forget", past: "forgot", pp: "forgotten", meaning: "ينسى" },
  { base: "forgive", past: "forgave", pp: "forgiven", meaning: "يسامح" },
  { base: "freeze", past: "froze", pp: "frozen", meaning: "يتجمد" },
  { base: "get", past: "got", pp: "gotten", meaning: "يحصل" },
  { base: "give", past: "gave", pp: "given", meaning: "يعطي" },
  { base: "go", past: "went", pp: "gone", meaning: "يذهب" },
  { base: "grow", past: "grew", pp: "grown", meaning: "ينمو" },
  { base: "hang", past: "hung", pp: "hung", meaning: "يعلق" },
  { base: "have", past: "had", pp: "had", meaning: "يملك" },
  { base: "hear", past: "heard", pp: "heard", meaning: "يسمع" },
  { base: "hide", past: "hid", pp: "hidden", meaning: "يخفي" },
  { base: "hit", past: "hit", pp: "hit", meaning: "يضرب" },
  { base: "hold", past: "held", pp: "held", meaning: "يمسك" },
  { base: "hurt", past: "hurt", pp: "hurt", meaning: "يؤذي" },
  { base: "keep", past: "kept", pp: "kept", meaning: "يحتفظ" },
  { base: "kneel", past: "knelt", pp: "knelt", meaning: "يركع" },
  { base: "know", past: "knew", pp: "known", meaning: "يعرف" },
  { base: "lay", past: "laid", pp: "laid", meaning: "يضع" },
  { base: "lead", past: "led", pp: "led", meaning: "يقود" },
  { base: "lean", past: "leant", pp: "leant", meaning: "يتكئ" },
  { base: "learn", past: "learnt", pp: "learnt", meaning: "يتعلم" },
  { base: "leave", past: "left", pp: "left", meaning: "يغادر" },
  { base: "lend", past: "lent", pp: "lent", meaning: "يقرض" },
  { base: "let", past: "let", pp: "let", meaning: "يدع" },
  { base: "lie", past: "lay", pp: "lain", meaning: "يرقد" },
  { base: "light", past: "lit", pp: "lit", meaning: "يشعل" },
  { base: "lose", past: "lost", pp: "lost", meaning: "يفقد" },
  { base: "make", past: "made", pp: "made", meaning: "يصنع" },
  { base: "mean", past: "meant", pp: "meant", meaning: "يعني" },
  { base: "meet", past: "met", pp: "met", meaning: "يقابل" },
  { base: "pay", past: "paid", pp: "paid", meaning: "يدفع" },
  { base: "put", past: "put", pp: "put", meaning: "يضع" },
  { base: "quit", past: "quit", pp: "quit", meaning: "يغادر" },
  { base: "read", past: "read", pp: "read", meaning: "يقرأ" },
  { base: "ride", past: "rode", pp: "ridden", meaning: "يركب" },
  { base: "ring", past: "rang", pp: "rung", meaning: "يرن" },
  { base: "rise", past: "rose", pp: "risen", meaning: "يرتفع" },
  { base: "run", past: "ran", pp: "run", meaning: "يجري" },
  { base: "say", past: "said", pp: "said", meaning: "يقول" },
  { base: "see", past: "saw", pp: "seen", meaning: "يرى" },
  { base: "seek", past: "sought", pp: "sought", meaning: "يبحث" },
  { base: "sell", past: "sold", pp: "sold", meaning: "يبيع" },
  { base: "send", past: "sent", pp: "sent", meaning: "يرسل" },
  { base: "set", past: "set", pp: "set", meaning: "يحدد" },
  { base: "shake", past: "shook", pp: "shaken", meaning: "يهز" },
  { base: "shine", past: "shone", pp: "shone", meaning: "يلمع" },
  { base: "shoot", past: "shot", pp: "shot", meaning: "يطلق" },
  { base: "show", past: "showed", pp: "shown", meaning: "يظهر" },
  { base: "shut", past: "shut", pp: "shut", meaning: "يغلق" },
  { base: "sing", past: "sang", pp: "sung", meaning: "يغني" },
  { base: "sink", past: "sank", pp: "sunk", meaning: "يغرق" },
  { base: "sit", past: "sat", pp: "sat", meaning: "يجلس" },
  { base: "sleep", past: "slept", pp: "slept", meaning: "ينام" },
  { base: "slide", past: "slid", pp: "slid", meaning: "ينزلق" },
  { base: "speak", past: "spoke", pp: "spoken", meaning: "يتكلم" },
  { base: "spend", past: "spent", pp: "spent", meaning: "ينفق" },
  { base: "spread", past: "spread", pp: "spread", meaning: "ينتشر" },
  { base: "stand", past: "stood", pp: "stood", meaning: "يقف" },
  { base: "steal", past: "stole", pp: "stolen", meaning: "يسرق" },
  { base: "stick", past: "stuck", pp: "stuck", meaning: "يلتصق" },
  { base: "strike", past: "struck", pp: "struck", meaning: "يضرب" },
  { base: "swim", past: "swam", pp: "swum", meaning: "يسبح" },
  { base: "take", past: "took", pp: "taken", meaning: "يأخذ" },
  { base: "teach", past: "taught", pp: "taught", meaning: "يعلم" },
  { base: "tear", past: "tore", pp: "torn", meaning: "يمزق" },
  { base: "tell", past: "told", pp: "told", meaning: "يخبر" },
  { base: "think", past: "thought", pp: "thought", meaning: "يفكر" },
  { base: "throw", past: "threw", pp: "thrown", meaning: "يرمي" },
  { base: "understand", past: "understood", pp: "understood", meaning: "يفهم" },
  { base: "wake", past: "woke", pp: "woken", meaning: "يستيقظ" },
  { base: "wear", past: "wore", pp: "worn", meaning: "يرتدي" },
  { base: "win", past: "won", pp: "won", meaning: "يفوز" },
  { base: "withdraw", past: "withdrew", pp: "withdrawn", meaning: "ينسحب" },
  { base: "write", past: "wrote", pp: "written", meaning: "يكتب" }
];

// ===== VOCABULARY UNITS =====
const VOCAB_UNITS = {
  "unit1": {
    title: "Unit 1: Education & Schooling",
    words: [
      { word: "compulsory", meaning: "إجباري" },
      { word: "curriculum", meaning: "منهاج دراسي" },
      { word: "tuition", meaning: "رسوم دراسية" },
      { word: "scholarship", meaning: "منحة دراسية" },
      { word: "enroll", meaning: "يسجل" },
      { word: "graduate", meaning: "يتخرج" },
      { word: "syllabus", meaning: "مقرر دراسي" },
      { word: "assignment", meaning: "واجب" },
      { word: "assessment", meaning: "تقييم" },
      { word: "literacy", meaning: "محو الأمية" }
    ]
  },
  "unit2": {
    title: "Unit 2: Immigration & Integration",
    words: [
      { word: "emigrate", meaning: "يهاجر" },
      { word: "immigrant", meaning: "مهاجر" },
      { word: "refugee", meaning: "لاجئ" },
      { word: "asylum", meaning: "ملجأ" },
      { word: "xenophobia", meaning: "كراهية الأجانب" },
      { word: "integration", meaning: "اندماج" },
      { word: "multicultural", meaning: "متعدد الثقافات" },
      { word: "diaspora", meaning: "شتات" },
      { word: "expatriate", meaning: "مغترب" },
      { word: "naturalization", meaning: "تجنس" }
    ]
  },
  "unit3": {
    title: "Unit 3: Environment & Ecology",
    words: [
      { word: "pollution", meaning: "تلوث" },
      { word: "deforestation", meaning: "إزالة الغابات" },
      { word: "renewable", meaning: "متجدد" },
      { word: "emissions", meaning: "انبعاثات" },
      { word: "conservation", meaning: "حفظ" },
      { word: "biodiversity", meaning: "تنوع بيولوجي" },
      { word: "sustainable", meaning: "مستدام" },
      { word: "ecosystem", meaning: "نظام بيئي" },
      { word: "carbon footprint", meaning: "بصمة كربونية" },
      { word: "global warming", meaning: "احتباس حراري" }
    ]
  },
  "unit4": {
    title: "Unit 4: Technology & Media",
    words: [
      { word: "innovation", meaning: "ابتكار" },
      { word: "artificial intelligence", meaning: "ذكاء اصطناعي" },
      { word: "digital", meaning: "رقمي" },
      { word: "cybersecurity", meaning: "أمن سيبراني" },
      { word: "encryption", meaning: "تشفير" },
      { word: "algorithm", meaning: "خوارزمية" },
      { word: "social media", meaning: "وسائل التواصل" },
      { word: "censorship", meaning: "رقابة" },
      { word: "misinformation", meaning: "معلومات مضللة" },
      { word: "privacy", meaning: "خصوصية" }
    ]
  },
  "unit5": {
    title: "Unit 5: Health & Wellness",
    words: [
      { word: "nutrition", meaning: "تغذية" },
      { word: "epidemic", meaning: "وباء" },
      { word: "vaccination", meaning: "تطعيم" },
      { word: "obesity", meaning: "سمنة" },
      { word: "mental health", meaning: "صحة نفسية" },
      { word: "therapy", meaning: "علاج" },
      { word: "diagnosis", meaning: "تشخيص" },
      { word: "hygiene", meaning: "نظافة" },
      { word: "surgery", meaning: "جراحة" },
      { word: "pharmacy", meaning: "صيدلية" }
    ]
  },
  "unit6": {
    title: "Unit 6: Economy & Development",
    words: [
      { word: "inflation", meaning: "تضخم" },
      { word: "recession", meaning: "ركود" },
      { word: "investment", meaning: "استثمار" },
      { word: "entrepreneurship", meaning: "مقاولة" },
      { word: "gross domestic product", meaning: "ناتج محلي إجمالي" },
      { word: "unemployment", meaning: "بطالة" },
      { word: "subsidy", meaning: "دعم" },
      { word: "privatization", meaning: "خصخصة" },
      { word: "globalization", meaning: "عولمة" },
      { word: "microfinance", meaning: "تمويل صغير" }
    ]
  },
  "unit7": {
    title: "Unit 7: Culture & Society",
    words: [
      { word: "heritage", meaning: "تراث" },
      { word: "diversity", meaning: "تنوع" },
      { word: "tolerance", meaning: "تسامح" },
      { word: "discrimination", meaning: "تمييز" },
      { word: "gender equality", meaning: "مساواة بين الجنسين" },
      { word: "stereotype", meaning: "صورة نمطية" },
      { word: "customs", meaning: "عادات" },
      { word: "tradition", meaning: "تقليد" },
      { word: "global village", meaning: "قرية عالمية" },
      { word: "cultural identity", meaning: "هوية ثقافية" }
    ]
  },
  "unit8": {
    title: "Unit 8: Human Rights & Citizenship",
    words: [
      { word: "democracy", meaning: "ديمقراطية" },
      { word: "justice", meaning: "عدالة" },
      { word: "equality", meaning: "مساواة" },
      { word: "freedom of speech", meaning: "حرية التعبير" },
      { word: "constitution", meaning: "دستور" },
      { word: "human dignity", meaning: "كرامة إنسانية" },
      { word: "solidarity", meaning: "تضامن" },
      { word: "citizenship", meaning: "مواطنة" },
      { word: "non-governmental", meaning: "غير حكومي" },
      { word: "advocacy", meaning: "مناصرة" }
    ]
  },
  "unit9": {
    title: "Unit 9: Science & Research",
    words: [
      { word: "experiment", meaning: "تجربة" },
      { word: "hypothesis", meaning: "فرضية" },
      { word: "laboratory", meaning: "مختبر" },
      { word: "phenomenon", meaning: "ظاهرة" },
      { word: "analysis", meaning: "تحليل" },
      { word: "scientific method", meaning: "منهج علمي" },
      { word: "peer review", meaning: "مراجعة الأقران" },
      { word: "breakthrough", meaning: "اختراق" },
      { word: "discovery", meaning: "اكتشاف" },
      { word: "innovation", meaning: "ابتكار" }
    ]
  },
  "unit10": {
    title: "Unit 10: Morocco & World Issues",
    words: [
      { word: "sovereignty", meaning: "سيادة" },
      { word: "diplomacy", meaning: "دبلوماسية" },
      { word: "Sahara", meaning: "الصحراء" },
      { word: "development", meaning: "تنمية" },
      { word: "infrastructure", meaning: "بنية تحتية" },
      { word: "tourism", meaning: "سياحة" },
      { word: "cooperation", meaning: "تعاون" },
      { word: "trade", meaning: "تجارة" },
      { word: "foreign policy", meaning: "سياسة خارجية" },
      { word: "peacekeeping", meaning: "حفظ السلام" }
    ]
  }
};
